import pandas as pd

category_data = {
    "category_code": [
        "44X72", "44Y72", "44Z72", "44W72", "44000", "4400A", "4400C", "441", 
        "441X", "4411", "44111", "44112", "4413", "4423X", "442", "4421", "4422", 
        "44221", "442299", "443", "443141", "443142", "444", "4441", "44412", 
        "44413", "445", "4451", "44511", "4453", "446", "44611", "447", "448", 
        "4481", "44811", "44812", "44814", "44819", "4482", "44831", "451", 
        "45111", "45112", "451211", "452", "4521E", "452112E", "452111E", 
        "4529", "45291", "45299", "453", "4532", "45321", "45322", "45330", 
        "454", "4541", "45431", "722", "7224", "7225", "722511", "72251X"
    ],
    "category_name": [
        "Retail Trade and Food Services", 
        "Retail Trade and Food Services, ex Auto",
        "Retail Trade and Food Services, ex Gas",
        "Retail Trade and Food Services, ex Auto and Gas",
        "Retail Trade", 
        "Retail Trade, ex Auto", 
        "GAFO", 
        "Motor Vehicle and Parts Dealers", 
        "Auto and Other Motor Vehicles", 
        "Automobile Dealers", 
        "New Car Dealers", 
        "Used Car Dealers", 
        "Automotive Parts, Accessories, and Tire Stores", 
        "Furniture, Home Furnishings, Electronics, and Appliance Stores", 
        "Furniture and Home Furnishings Stores", 
        "Furniture Stores", 
        "Home Furnishings Stores", 
        "Floor Covering Stores", 
        "All Other Home Furnishings Stores", 
        "Electronics and Appliance Stores", 
        "Household Appliance Stores", 
        "Electronics Stores", 
        "Building Material and Garden Equipment and Supplies Dealers", 
        "Building Material and Supplies Dealers", 
        "Paint and Wallpaper Stores", 
        "Hardware Stores", 
        "Food and Beverage Stores", 
        "Grocery Stores", 
        "Supermarkets and Other Grocery (Except Convenience) Stores", 
        "Beer, Wine, and Liquor Stores", 
        "Health and Personal Care Stores", 
        "Pharmacies and Drug Stores", 
        "Gasoline Stations", 
        "Clothing and Clothing Accessories Stores", 
        "Clothing Stores", 
        "Men's Clothing Stores", 
        "Women's Clothing Stores", 
        "Family Clothing Stores", 
        "Other Clothing Stores", 
        "Shoe Stores", 
        "Jewelry Stores", 
        "Sporting Goods, Hobby, Musical Instrument, and Book Stores", 
        "Sporting Goods Stores", 
        "Hobby, Toy, and Game Stores", 
        "Book Stores", 
        "General Merchandise Stores", 
        "Department Stores", 
        "Discount Department Stores", 
        "Department Stores (Excl. Discount Department Stores)", 
        "Other General Merchandise Stores", 
        "Warehouse Clubs and Superstores", 
        "All Other General Merchandise Stores", 
        "Miscellaneous Store Retailers", 
        "Office Supplies, Stationery, and Gift Stores", 
        "Office Supplies and Stationery Stores", 
        "Gift, Novelty, and Souvenir Stores", 
        "Used Merchandise Stores", 
        "Nonstore Retailers", 
        "Electronic Shopping and Mail-order Houses", 
        "Fuel Dealers", 
        "Food Services and Drinking Places", 
        "Drinking Places", 
        "Restaurants and Other Eating Places", 
        "Full Service Restaurants", 
        "Limited Service Eating Places"
    ],
    "high_level_category": [
        "Retail Trade and Food Services",
        "Retail Trade and Food Services", "Retail Trade and Food Services", 
        "Retail Trade and Food Services", "Retail Trade and Food Services", 
        "Retail Trade and Food Services", "Retail Trade and Food Services", 
        "Motor Vehicle and Parts Dealers", "Motor Vehicle and Parts Dealers", 
        "Motor Vehicle and Parts Dealers", "Motor Vehicle and Parts Dealers", 
        "Motor Vehicle and Parts Dealers", "Motor Vehicle and Parts Dealers", 
        "Furniture, Home Furnishings, Electronics, and Appliance Stores", 
        "Furniture and Home Furnishings Stores", "Furniture and Home Furnishings Stores", 
        "Furniture and Home Furnishings Stores", "Furniture and Home Furnishings Stores", 
        "Furniture and Home Furnishings Stores", "Electronics and Appliance Stores", 
        "Electronics and Appliance Stores", "Electronics and Appliance Stores", 
        "Building Material and Garden Equipment and Supplies Dealers", 
        "Building Material and Garden Equipment and Supplies Dealers", 
        "Building Material and Garden Equipment and Supplies Dealers", 
        "Building Material and Garden Equipment and Supplies Dealers", 
        "Food and Beverage Stores", "Food and Beverage Stores", 
        "Food and Beverage Stores", "Food and Beverage Stores", 
        "Health and Personal Care Stores", 
        "Health and Personal Care Stores", "Gasoline Stations", 
        "Clothing and Clothing Accessories Stores", 
        "Clothing and Clothing Accessories Stores", 
        "Clothing and Clothing Accessories Stores", 
        "Clothing and Clothing Accessories Stores", 
        "Clothing and Clothing Accessories Stores", 
        "Clothing and Clothing Accessories Stores", 
        "Clothing and Clothing Accessories Stores", 
        "Clothing and Clothing Accessories Stores", 
        "Sporting Goods, Hobby, Musical Instrument, and Book Stores", 
        "Sporting Goods, Hobby, Musical Instrument, and Book Stores", 
        "Sporting Goods, Hobby, Musical Instrument, and Book Stores", 
        "Sporting Goods, Hobby, Musical Instrument, and Book Stores", 
        "General Merchandise Stores", "Department Stores", 
        "Department Stores", "Department Stores", 
        "Other General Merchandise Stores", "Other General Merchandise Stores", 
        "Other General Merchandise Stores", "Miscellaneous Store Retailers", 
        "Miscellaneous Store Retailers", 
        "Miscellaneous Store Retailers", 
        "Miscellaneous Store Retailers", 
        "Miscellaneous Store Retailers", "Nonstore Retailers", 
        "Nonstore Retailers", 
        "Gasoline Stations", 
        "Food Services and Drinking Places", "Food Services and Drinking Places", 
        "Food Services and Drinking Places", "Food Services and Drinking Places", 
        "Food Services and Drinking Places"
    ],
    "is_subset": [  # Ensure all lists align in length
        False, True, True, True, True, True, True,
        False, True, True, True, True, True,
        False, False, True, True, True, True,
        False, True, True,
        False, True, True, True,
        False, True, True, True,
        False, True,
        False,
        False, True, True, True, True, True, True, True,
        False, True, True, True,
        False, False, True, True,
        False, True, True, 
        False, True, True, True, True,
        False, True,
        True,
        False, True, True, True, True
    ]
}

for key, value in category_data.items():
    print(f"{key}: {len(value)}")
categories_df = pd.DataFrame(category_data)

categories_df.to_csv("../data/mrts_code_categories.csv", index=False)

print("MRTS categories data saved.")
